# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs

jobs:
  generate_apk:
    resource_class: large
    docker:
      - image: ghcr.io/cirruslabs/flutter:3.22.3
    steps:
      - checkout          
      - run:
          name: Build APK
          command: |
            flutter build apk --release
      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk
          destination: app-release.apk

workflows:
  # Manual workflow for production build
  build:
    jobs:
      - generate_apk